[project]
name = "rxcube"
version = "0.2.0"
description = "Play rubix cube on terminal"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "colorama>=0.4.6",
    "pytest>=8.4.2",
]
[project.scripts]
rxcube-cli = "rxcube.main:main"
